### ISSUE TITLE
Can it be compiled on mac os?

### ISSUE THREAD

**Issue by k1ller13** [giongto35/cloud-morph#12]
Sorry to disturb, I'm the rookie in cloud gaming/streaming media programming. I'm using Mac OS, but it doesn't work by your step. Here is the result. 
![image](https://user-images.githubusercontent.com/43134418/93581245-74ba3f00-f9d3-11ea-92b1-de4e2c5e8ef1.png)

It stacks in "2020/09/18 17:15:50 Launched application VM", Then has no outputs. I checked docker logs, here is the result.
![image](https://user-images.githubusercontent.com/43134418/93581010-25740e80-f9d3-11ea-8d95-4256e37866b1.png)
Can you give me some advice? I'm newer in this field, but I want to study.

**Comment by giongto35** [comment]
Oh I never try running it on MacOS. MacOS doesn't seem like using X11, so it should not be compatible now.

**Comment by killer-peng** [comment]
> Oh I never try running it on MacOS. MacOS doesn't seem like using X11, so it should not be compatible now.

Thanks for your reply. Is there any solution that can run in Mac OS?

**Comment by giongto35** [comment]
@killer-peng I think the only solution now is running an Ubuntu VM in MacOS. As I read from internet, XQuartz is an alternative for X11 on Mac. I will spend time working on this issue this weekend . 
Thank you for raising it, I totally forgot that it doesn't work on MacOS when it is a popular development platform.

**Comment by killer-peng** [comment]
> @killer-peng I think the only solution now is running an Ubuntu VM in MacOS. As I read from internet, XQuartz is an alternative for X11 on Mac. I will spend time working on this issue this weekend .
> Thank you for raising it, I totally forgot that it doesn't work on MacOS when it is a popular development platform.

Thank you very much.

**Comment by giongto35** [comment]
I took few days to investigate the issue. Resolved here: https://github.com/giongto35/cloud-morph/pull/47
X11 is not the problem. It's container issue between Linux and Mac. Linux has Docker-host, so it can communicate with OS port directly, while Container in Mac has to communicate using "host.docker.internal" domain.
