### ISSUE TITLE
execing run-client.sh  panic: exit status 126

### ISSUE THREAD

**Issue by plutoxiao** [giongto35/cloud-morph#19]
I am deploying this project on Ubuntu18.04 and I've done steps one to four. But when I run "go run server.go", there are some problems:

2020/10/22 15:39:38 Starting monitoring server at :3535
2020/10/22 15:39:38 Profiling is enabled at :3535/debug/pprof
2020/10/22 15:39:38 Spawn server
2020/10/22 15:39:38 listening wine at port 9090
2020/10/22 15:39:38 execing run-client.sh
panic: exit status 126

goroutine 1 [running]:
github.com/giongto35/cloud-morph/pkg/core/go/cloudgame.(*ccImpl).launchGameVM(0xc00007f9e0, 0x138c, 0xc000024c80, 0x17, 0xc00002a980, 0xd, 0xc00002a9b0, 0x9, 0x406900, 0x140)
	    cloud-morph/pkg/core/go/cloudgame/cloudgame.go:141 +0x340
github.com/giongto35/cloud-morph/pkg/core/go/cloudgame.NewCloudGameClient(0xc000024c80, 0x17, 0xc00002a980, 0xd, 0xc00002a9b0, 0x9, 0x0, 0xc00002aa10, 0xd, 0xc00002a9e0, ...)
	    cloud-morph/pkg/core/go/cloudgame/cloudgame.go:75 +0x1db
github.com/giongto35/cloud-morph/pkg/core/go/cloudgame.NewCloudService(0xc000024c80, 0x17, 0xc00002a980, 0xd, 0xc00002a9b0, 0x9, 0x0, 0xc00002aa10, 0xd, 0xc00002a9e0, ...)
	    cloud-morph/pkg/core/go/cloudgame/service.go:304 +0x1ac
main.NewServer(0xf490c0)
	    cloud-morph/server.go:230 +0x44e
main.main()
	cloud-morph/server.go:296 +0xb8
exit status 2

**Comment by sergystepanov** [comment]
It seems that you are trying to run an old version of the app where that script (maybe) isn't marked as executable. Does this error persist in the current app snapshot?

```
$ git ls-tree -r HEAD
100755 blob bc553a5b62d3c0acf6f908568e7001fa87de040a    run-wine-nodocker.sh
100755 blob f90c230aeaf48e7a2c17c25a3f05184dd011c8cf    run-wine.sh
100755 blob 8440092efb8a7413c9b3b46c67d4411eca7799f2    setup.sh
100644 blob 66125993d608fff1669f83f60da009f7b2927251    winvm/download_gecko_and_mono.sh
100755 blob 65b48d68b64bd578d91559f5aa24e271fc46f995    winvm/run.sh
100755 blob 1b708b7b5f3512c2081d39c4e7386849830d9936    winvm/test-docker.sh
```
@giongto35, you forgot to set executable bit for `download_gecko_and_mono.sh`. No idea if you need that file but there will be similar errors if you use it.

**Comment by giongto35** [comment]
@plutoxiao I just made a quick look and still see no problem with it. Are you running with `notepad` or different exe file? 
Can you run `ls -alh` in your cloned folder, there might be possibility that the script isn't marked as executable.

**Comment by sergystepanov** [comment]
FYI, I tried to run it for the first time and (after half of an hour setup.sh installation (: [gee, that's a lot of dependencies]) it works out of the box, it seems.

![image](https://user-images.githubusercontent.com/846874/97118980-53f5af80-171e-11eb-8b5b-f4f8d19263cc.png)

**Comment by giongto35** [comment]
@sergystepanov : D. Thanks for testing it. 
Most of the time is to build docker image. I think I can optimize with docker multistage build like in CloudRetro.

**Comment by plutoxiao** [comment]
@giongto35 @sergystepanov: Many thanks for your reply. I have solved this problem.
