### ISSUE TITLE
Will be there a way to use native linux applications

### ISSUE THREAD

**Issue by kadogo** [giongto35/cloud-morph#22]
Hello,

At first thanks for this project, I was looking for some cloud gaming solution but made with opensource. It's more a question than a real issue but do you think it would be possible to use the same process for running a native linux application/game instead of Windows applications with Wine?

Cheers.

**Comment by giongto35** [comment]
Sorry for the late reply. It's possible and will be much easy but I don't support it now because I think Window offers more applications. Linux is very limited in term of game support.

**Comment by kadogo** [comment]
No problem. Thanks, it's because I read that it was based on Wine and sadly sometmes Wine not always work.

I think supporting Linux binaries could go further by using for example stuff like Lutris or Steam that are also helping for the compatibility with Wine but with much more stuff around. The two at end can use Wine for compatibility but with much patches and other software that are working together.

**Comment by giongto35** [comment]
Thanks!
Yes, I didn't know about Lutris when I started this project but Lutris must be the way to go. Lutris is also based on Wine to setup linux environment but more convenient and support.
I have it in plan, currently Im trying to setup the infrastructure first. : D

**Comment by kadogo** [comment]
Yes I think supporting lutris (or any linux binaries at end) is what is needed.
Steam can be usefull but they already have "remote play" so we can just launch Steam with something like X2Go and connect through another Steam Client.
