### ISSUE TITLE
Is it possible to run server on windows natively?

### ISSUE THREAD

**Issue by dimutch833** [giongto35/cloud-morph#27]
My OS : Windows 10 1909 x64

**Comment by sergystepanov** [comment]
@dimutch833, it's not possible and not meant to be used in such way, without some isolation layer (VM, Wine). Just curious, what's your use case?

**Comment by dimutch833** [comment]
@sergystepanov Games with dx9,dx11

**Comment by sergystepanov** [comment]
I meant why do you need to run the app on windows natively? Have you tried cloud-morph yet? Compatibility issues? A Linux with Wine can run DX9-11 games with [dxvk](https://github.com/doitsujin/dxvk).
(btw, I can speak Russian if you prefer that)

**Comment by dimutch833** [comment]
> 
> 
> I meant why do you need to run the app on windows natively? Have you tried cloud-morph yourself yet? Compatibility issues? A Linux with Wine can run DX9-11 games with [dxvk](https://github.com/doitsujin/dxvk).
> (btw, I can speak Russian if you prefer that)

1.i dont want to change windows to linux 
2.I cant try because 1 , only cloud-diablo  that already hosted by another
3.Cuz im using windows

**Comment by giongto35** [comment]
Yes, currently the server is not able to run on window. The whole stack is on Linux as well.
Window and Linux have very different ways of programmatical manipulation on native apps: to capture screen, trigger keys. I decided to write the server on Linux because it is more developers' friendly.

**Comment by sergystepanov** [comment]
You could try [WSL2](https://ubuntu.com/blog/ubuntu-on-wsl-2-is-generally-available). (:
