### ISSUE TITLE
Road Rash Demo Freezes at 'Save Game As...'

### ISSUE THREAD

**Issue by brandonbyskov** [giongto35/cloud-morph#54]
The Road Rash demo froze when trying to use the 'Save Game As...' menu item from the Restroom. This feature opens a Windows save dialog box to save a game file.

When selecting 'Save Game As...', the save dialog opened correctly. When trying to interact with the dialog to save a file, the dialog disappeared from the screen and the focus was changed back to the game menu. the screen was frozen on the game Restroom menu and no user input was accepted.

**Comment by giongto35** [comment]
Thanks for reporting the issue, seems like there will be a problem if there is dialog. It requires switching between two windows focus. It is worth noticing, but currently I think I don't have the bandwidth to fix it.
