### ISSUE TITLE
Unity games support

### ISSUE THREAD

**Issue by alessiobottosso** [giongto35/cloud-morph#64]
Hi,
We made a Windows game with Unity. When deployed to cloud morph, the game starts but the input does not work (the game locally works with mouse and keyboard and with gamepad).
We enabled some logs in the game and we also made a simpler game only to test the inputs, but we get a black screen.

Any suggestion? Are Unity games supported/Are there some tips when building the game (i.e. x86 vs x64, supported graphics APIs, etc.)? Thanks in advance.

**Comment by giongto35** [comment]
Hi @alessiobottosso ,
Thanks cvery much for trying Cloud Morph.
When you say you deployed to Cloud Morph, is it deploy to a remote machine or just trying to run it with CloudMorph locally? Do you successfully run CloudMorph project with your game on local machine?
I haven't tried any Unity games. Currently, CloudMorph may fail to support game-demanding GPU. Can you send me your simple game. It will be nice for me to experiment with that.
Btw, The way input work is searching the Windows Application based on "WindowsTitle" and send Windows Event. If the Input is DirectX Input, I'm not sure if it work. To debug Input, you can try accessing docker, and run `supervisorctl status` inside the docker see the status of `syncinput` app.

**Comment by alessiobottosso** [comment]
hI @giongto35,
Many thanks for your quick answer.
Can you provide me an email to send you the projects?

Thanks in advance,
Alessio

**Comment by giongto35** [comment]
Thanks @alessiobottosso, Can you send it to giongto35@gmail.com

**Comment by Ifeanyichuku** [comment]
Hi. and thanks. facing the same issue  Any solution you can share on this. An implementation of this will help.  thanks once again

**Comment by giongto35** [comment]
Hi @Ifeanyichuku, are you running on Linux env? you can try running on Windows OS.

**Comment by urbyte** [comment]
How to configure unity games

**Comment by sergystepanov** [comment]
No idea.
