### ISSUE TITLE
Display the real-time latency

### ISSUE THREAD

**Issue by tianrenz2** [giongto35/cloud-morph#67]
I wonder if the latency from the web client to the server could be displayed during the play, since it might be a useful indication for users who are suffering a big lag and wondering why.

**Comment by giongto35** [comment]
Hi @tianrenz2, where do you want to display the latency. In the discovery on the left, you can see the ping, do you want to show on the screen . This simple latency check is by sending a HTTP request to server and check response time. 
https://github.com/giongto35/cloud-morph/blob/master/web/js/controller.js#L137

**Comment by tianrenz2** [comment]
@giongto35 thanks for answering 👍 , I just noticed that.
