### ISSUE TITLE
No work

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-morph#7]
It has been showing a black screen on DII since today, is it normal?
I was able to run around a bit with a necromancer and then, after the page reload, it all went black. It was possible to play if multiple tabs were open, in which case the first one would stream the game.

**Comment by giongto35** [comment]
Hi @sergystepanov ,
:D I was modifying some code last few hours. I just finish, can you try http://clouddiablo.com/ again? It should be able to load now. 

The expected behavior in multitab is that all will share the same game. 
![image](https://user-images.githubusercontent.com/7755543/92332976-27290280-f0b4-11ea-9269-2f2ecf8cfb3c.png)

Currently, it's quite spiky for some reason I haven't got time to investigate. It happens in local as well.

**Comment by sergystepanov** [comment]
Cool! Seems to be working now.

![изображение](https://user-images.githubusercontent.com/846874/92333421-11a0e200-f08e-11ea-89e0-3d97132a4018.png)

**Comment by sergystepanov** [comment]
It will be interesting to see how you will optimize the mouse pointer tracking :P
Kinda playable with Singaporean ping 300.

![d21](https://user-images.githubusercontent.com/846874/92417757-864a4e00-f16c-11ea-9f60-8aee0d438da8.gif)

**Comment by giongto35** [comment]
How can you show the ping like that :D.
Good to see how it works with 300 ping. Seems playable.
I think that lag = the delay of frame + the mouse click event.
Currently, I only track mouse click but mouse movement should be tracked as well. It will help to run FPS (Counter Strike), RTS (AOE) game.
Some ideas I have in mind are: Using UDP + optimize payload + Predict the future like what you read in Stadia article (mouse movement is mostly linear).

**Comment by sergystepanov** [comment]
Yeah, and it's good that they've started to add low-level API for in-browser pointer movements ([coalesced](https://pspdfkit.com/blog/2019/using-getcoalescedevents/), predicted) which would help with smoothening the movement for better user exp.
[Negative latency](https://nolannicholson.com/2019/12/16/exploring-negative-latency.html) as a theory is rather straightforward, but in order to implement even the easiest RetroArch method (game snapshots inside some VM: Wine running inside Docker in Docker in a cloud container (::: ), this would require some pretty beefy computer, not to mention a prediction cloud cluster to render possible outcomes.
Actually, it's a great research topic for a thesis. (:

**Comment by giongto35** [comment]
oh :O, Thank you for the low-level API for in-browser pointer movements article. Really nice.
Yes, I think I just try some easy ones first and let see how. Negative latency is too much :))
