### ISSUE TITLE
panic: listen udp :5004: bind: address already in use

### ISSUE THREAD

**Issue by ImanCol** [giongto35/cloud-morph#72]
Hi there. I am starting to test this. Use Ubuntu 20.04 on Windows. I did some pre-installations to get it working, as always. The issue is that when it is running, it reaches a point where it shows me a Firewall window, but the whole process stops, This is the message.

```
2021/08/27 00:35:07 Launched application VM
2021/08/27 00:35:07 Setup Video Listener
panic: listen udp :5004: bind: address already in use

goroutine 1 [running]:
github.com/giongto35/cloud-morph/pkg/core/go/cloudapp.(*ccImpl).newLocalStreamListener(0xc0001044b0, 0x138c, 0x1, 0xc0000ec860)
        /home/evan/cloud-morph/pkg/core/go/cloudapp/cloudapp.go:232 +0x26b
github.com/giongto35/cloud-morph/pkg/core/go/cloudapp.NewCloudAppClient(0xc0000ec860, 0x6, 0xc0000ec870, 0xb, 0xc0000ec890, 0x7, 0x0, 0xc0000ec8c0, 0xd, 0xc0000ec8a7, ...)
        /home/evan/cloud-morph/pkg/core/go/cloudapp/cloudapp.go:91 +0x375
github.com/giongto35/cloud-morph/pkg/core/go/cloudapp.NewCloudService(0xc0000ec860, 0x6, 0xc0000ec870, 0xb, 0xc0000ec890, 0x7, 0x0, 0xc0000ec8c0, 0xd, 0xc0000ec8a7, ...)
        /home/evan/cloud-morph/pkg/core/go/cloudapp/service.go:276 +0xf7
github.com/giongto35/cloud-morph/pkg/core/go/cloudapp.NewServerWithHTTPServerMux(0xc0000ec860, 0x6, 0xc0000ec870, 0xb, 0xc0000ec890, 0x7, 0x0, 0xc0000ec8c0, 0xd, 0xc0000ec8a7, ...)
        /home/evan/cloud-morph/pkg/core/go/cloudapp/server.go:71 +0x26c
main.NewServer(0xfcaee0)
        /home/evan/cloud-morph/server.go:211 +0x4fd
main.main()
        /home/evan/cloud-morph/server.go:314 +0xb8
exit status 2
```
![image](https://user-images.githubusercontent.com/26169049/131077286-1558f1a4-fe50-4af4-99ce-d4ac0f139b35.png)

**Comment by giongto35** [comment]
It seems like a common issue, it's like the port 5004 is taken. Can you check if any service is listening at that port : "lsof -i tcp:5004"
And if you have any follow up, you can contact me via Discord. I'm more available there for answer. https://discord.gg/ux2rDqwu2W

**Comment by ImanCol** [comment]
it was indeed a windows process
![image](https://user-images.githubusercontent.com/26169049/132882958-b3a834c7-afec-4bfa-aaa1-d91ae8d8a51f.png)
![image](https://user-images.githubusercontent.com/26169049/132883083-cfbaff4e-18b5-4bf6-9a11-279e1ad8473a.png)
