### ISSUE TITLE
How does v-GPU work？

### ISSUE THREAD

**Issue by xiaodeedaijia** [giongto35/cloud-morph#84]
It supports v-gpu？if not，how does it support multi-doker if many user use one server to play？
I am thinking about whether i can use nvdia‘s v-gpu to support my server.

**Comment by giongto35** [comment]
yeah, I tried introducing Virtual GPU with VGL here https://github.com/giongto35/cloud-morph/pull/68/files . However, It's not successful and CloudMorph doesn't support Virtual GPU on Linux now.
Currently, I try running CloudMorph on Windows with Windows Sandbox. Windows Sandbox has Virtual GPU going together

**Comment by xiaodeedaijia** [comment]
@giongto35 Thanks for your reply(*^▽^*)👍.My English is poor,and this is the first time I have post issues in github(*^▽^*).

**Comment by giongto35** [comment]
@xiaodeedaijia You re welcome. It's always great to speak up and I really appreciate your feedback. It shows that my project gets attention!
